### ISSUE TITLE
sqlit3

### ISSUE THREAD

**Issue by Vaegskylt** [pathmann/pyTSon#112]
It seems like I cannot import sqlite3 properly, posting here desperately for help 👍 

`2018-12-12 23:57:00	pyTSon.PluginHost.reload	Error	Error loading python plugin from H:/Program Files/TeamSpeak 3 Client/config/plugins/pyTSon\scripts\tsbot\: Traceback (most recent call last):

  File "H:/Program Files/TeamSpeak 3 Client/config/plugins/pyTSon/scripts\pluginhost.py", line 322, in reload
    cls.modules[base] = importlib.__import__(base)

  File "<frozen importlib._bootstrap>", line 1055, in __import__
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "H:/Program Files/TeamSpeak 3 Client/config/plugins/pyTSon/scripts\tsbot\__init__.py", line 7, in <module>
    import channelupdate

  File "H:\Program Files\TeamSpeak 3 Client\config\plugins\pyTSon\scripts\tsbot\channelupdate.py", line 4, in <module>
    import database
  File "H:\Program Files\TeamSpeak 3 Client\config\plugins\pyTSon\scripts\tsbot\database.py", line 4, in <module>
    import sqlite3
  File "H:/Program Files/TeamSpeak 3 Client/config/plugins/pyTSon/lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *

  File "H:/Program Files/TeamSpeak 3 Client/config/plugins/pyTSon/lib\sqlite3\dbapi2.py", line 50, in <module>
    version_info = tuple([int(x) for x in version.split(".")])
NameError: name 'version' is not defined
`

**Comment by Vaegskylt** [comment]
After reinstalling pYTson completely I now get this error instead

    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by pathmann** [comment]
Yeah, I think I missed some important files bundling the windows plugin.
If you wanna test it, you can download python from [here](https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-amd64.zip) for 64bit or from [here](https://www.python.org/ftp/python/3.5.2/python-3.5.2-embed-win32.zip) for 32bit and copy the file sqlite3.dll to %APPDATA%\TS3Client\plugins\pyTSon\lib\lib-dynload (I hope I got the path right on windows).

**Comment by Vaegskylt** [comment]
Reinstalled sqlite3 completely and moved the sqlite3.dll to the path you suggested and now it's working like a charm again
Thanks a ton!

**Comment by pathmann** [comment]
Should be fixed in e3abd16.

Please retest with the build from here https://repo.4qt.de/pyTSon/nightlies/2018-12-14/e3abd16/ (as soon as [the build](https://build.4qt.de/job/pyTSon/195/) is completed.
