### ISSUE TITLE
[Question] ValueError: Could not find matching overload for given arguments

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#61]
```
4/11/2017 22:31:11	pyTSon	Error	Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\addonList\__init__.py", line 123, in __init__
    super(QDialog, self).__init__(parent)
ValueError: Could not find matching overload for given arguments:
('Guest',)
 The following slots are available:
QDialog(QWidget parent, Qt::WindowFlags f) -> QDialog
QDialog() -> QDialog
QDialog(QWidget parent) -> QDialog

	
4/11/2017 22:31:11	pyTSon	Error	Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\addonList\__init__.py", line 49, in onMenuItemEvent
    self.dlg.show()
ValueError: Trying to call 'show' on a destroyed QDialog object
```

what am i doing wrong this time? :/

```py
    def onMenuItemEvent(self, schid, atype, menuItemID, selectedItemID):
        if atype == ts3defines.PluginMenuType.PLUGIN_MENU_TYPE_CLIENT and menuItemID == 0:
            try:
                (error, name) = ts3lib.getClientVariableAsString(schid, selectedItemID, ts3defines.ClientProperties.CLIENT_NICKNAME)
                addons = self.parseMeta(schid,selectedItemID)
                if not self.dlg: self.dlg = AddonsDialog(schid, addons, name)
                self.dlg.show()
                self.dlg.raise_()
                self.dlg.activateWindow()
            except: from traceback import format_exc;ts3lib.logMessage(format_exc(), ts3defines.LogLevel.LogLevel_ERROR, "pyTSon", 0)
```

```py
class AddonsDialog(QDialog):
    def __init__(self, addons, name, parent=None):
        try:
            super(QDialog, self).__init__(parent)
            setupUi(self, path.join(pytson.getPluginPath(), "ressources", "ui", "pyTSon-configdialog.ui"))
            self.setAttribute(Qt.WA_DeleteOnClose)
            self.setWindowTitle("{0}'s Addons".format(name))
            self.tabWidget.setTabEnabled(1, False)
            self.tabWidget.setTabEnabled(2, False)
            self.differentApiButton.setDisabled(True)
            self.reloadButton.setDisabled(True)
            self.repositoryButton.setDisabled(True)
            self.requiredApiEdit.setDisabled(True)
            #self.addonList.addItems()
        except: from traceback import format_exc;ts3lib.logMessage(format_exc(), ts3defines.LogLevel.LogLevel_ERROR, "pyTSon", 0)
```

**Comment by pathmann** [comment]
The exception tells you what's wrong.

You are trying to call the constructor of QDialog with one argument of type string (with value 'Guest').
QDialog has three valid constructors:
1. QDialog(QWidget parent, Qt::WindowFlags f) -> QDialog
2. QDialog() -> QDialog
3. QDialog(QWidget parent) -> QDialog

None of them matches your call.

Your specific error is, that you don't use your own class as defined. You are instantiate an object of type AddonsDialog with this constructor: AddonsDialog(schid, addons, name)

Your constructor looks as follows: def __init__(self, addons, name, parent=None)
So the python interpreter will substitute the arguments as follows: addons=schid, name=addons, parent=name. Then parent is used as argument of the super (QDialog) constructor.
Simple as that.

**Comment by Bluscream** [comment]
Damn, why was the schid argument even there in the first place and how did i not see it :(
