### ISSUE TITLE
AttributeError: 'IconPack' object has no attribute 'settings'

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#64]
```
5/12/2017 18:26:48	pyTSon	Error	Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\channelGroupChanger\__init__.py", line 83, in __init__
    item.setIcon(QIcon(IconPack.icon(icons,"group_%s"%p[1])))
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\ts3client.py", line 455, in icon
    if not self.settings.has_option("gfxfiles", var):
AttributeError: 'IconPack' object has no attribute 'settings'
```
Code reference: https://github.com/Bluscream/pyTSon_plugins/blob/master/channelGroupChanger/__init__.py#L83
P.S. The ServerCache function works fine with the 'same' arguments on the other hand 🤔

**Comment by Bluscream** [comment]
Fixed by using open and close
