### ISSUE TITLE
Cant open "settings" since 1.2.0

### ISSUE THREAD

**Issue by gitmuss** [pathmann/pyTSon#67]
"Exception: Error creating widget from uifile" when trying to open settings

**Comment by pathmann** [comment]
Do you mean pyTSon's settings or some settings dialog of a plugin? 
If the latter, can you please attach your ui file?

**Comment by gitmuss** [comment]
yes pyTson´s settings

**Comment by gitmuss** [comment]
Traceback (most recent call last):
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 378, in callMethod
    return meth(*args)
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 626, in onMenuItemEvent
    cls.configure()
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 368, in configure
    cls.confdlg = ConfigurationDialog(cls.cfg, cls, mainwindow)
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\config.py", line 92, in __init__
    raise e
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\config.py", line 84, in __init__
    widgets=self.CONF_WIDGETS)
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\__init__.py", line 291, in setupUi
    raise Exception("Error creating widget from uifile")

**Comment by pathmann** [comment]
I can't reproduce it here. Which platform are you running on?

**Comment by gitmuss** [comment]
Windows 10

**Comment by pathmann** [comment]
64 bit?

**Comment by gitmuss** [comment]
yes

**Comment by pathmann** [comment]
OK, I have no Windows 10 vm, but I doubt that it makes any difference. I'll look into it.

**Comment by gitmuss** [comment]
ok ty

**Comment by Bluscream** [comment]
I'm pretty sure this will turn out as a duplicate to my previous reported bug.
Are you sure you updated the x86 package aswell?

**Comment by pathmann** [comment]
And I'm pretty sure it's not. If the file could not be located, there would be another exception.

**Comment by pathmann** [comment]
Could you pls change line 291 in pytsonui/\_\_init\_\_.py to:
```python
raise Exception("Error creating widget from uifile %s" % loader.errorString()) 
```
and post the output again here?

**Comment by BradyThe** [comment]
> An error has occurred while reading the UI file at line 1, column 0: Premature end of document.

It looks like pyTSon-configdialog.ui broke in the 64bit installer. It has a file size of 0 bytes. I downloaded the 32bit installer, replaced the respective file, and now everything works as intended.

**Comment by Bluscream** [comment]
That helped me fixing the myTeamspeak version :)

**Comment by pathmann** [comment]
If I download the archives (both 32 and 64 bit windows) and open them with any zip tool, the files are fine.

I added two files manually to the bundles (the ui file and the license file) to fix #63 and #66, so I guess my archive manager used another compression method than the original bundle script, so that the TS3 client's package installer is getting confused by that.


This should be only temporary, I provide new packages in the next few days.

**Comment by Scrxtchy** [comment]
I hit this issue as well once I got the update working

**Comment by gitmuss** [comment]
still does not work

Traceback (most recent call last):
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 378, in callMethod
    return meth(*args)
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 626, in onMenuItemEvent
    cls.configure()
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 368, in configure
    cls.confdlg = ConfigurationDialog(cls.cfg, cls, mainwindow)
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\config.py", line 92, in __init__
    raise e
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\config.py", line 84, in __init__
    widgets=self.CONF_WIDGETS)
  File "C:/Users/User1/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\__init__.py", line 291, in setupUi
    raise Exception("Error creating widget from uifile %s" % loader.errorString())
Exception: Error creating widget from uifile An error has occurred while reading the UI file at line 1, column 0: Vorzeitiges Ende des Dokuments.

**Comment by pathmann** [comment]
As a quick fix, you can replace the file %PLUGIN_DIR%/pyTSon/ressources/pyTSon-configdialog.ui with this file: https://raw.githubusercontent.com/pathmann/pyTSon/v1.2.0/ressources/ui/pyTSon-configdialog.ui

**Comment by gitmuss** [comment]
Same again

**Comment by Scrxtchy** [comment]
Hotfix worked

**Comment by gitmuss** [comment]
Ty worked fine :)
