### ISSUE TITLE
reloading the plugin destroys some PythonQt support

### ISSUE THREAD

**Issue by pathmann** [pathmann/pyTSon#7]
If you reload pyTSon, it refuses to convert Qt enums.
1. Start client
2. Show the console (should work) and close it.
3. Reload pyTSon
4. Try to show the console (won't work).

Traceback:

```
Traceback (most recent call last):
  File "/home/thomas/.ts3client/plugins/pyTSon/scripts/ts3plugin.py", line 167, in callMethod
    return meth(*args)
  File "/home/thomas/.ts3client/plugins/pyTSon/scripts/ts3plugin.py", line 245, in onMenuItemEvent
    cls.showScriptingConsole()
  File "/home/thomas/.ts3client/plugins/pyTSon/scripts/ts3plugin.py", line 145, in showScriptingConsole
    cls.shell = PythonConsole(cls.cfg.getboolean("console", "tabcomplete"), cls.cfg.getboolean("console", "spaces"), cls.cfg.getint("console", "tabwidth"), QFont(cls.cfg.get("console", "fontFamily"), cls.cfg.getint("console", "fontSize")), QColor(cls.cfg.get("console", "backgroundColor")), QColor(cls.cfg.get("console", "textColor")), cls.cfg.getint("console", "width"), cls.cfg.getint("console", "height"))
  File "/home/thomas/.ts3client/plugins/pyTSon/include/pytsonui.py", line 304, in __init__
    self.selformat.setBackground(Qt.white)
ValueError: Called setBackground(QBrush brush) -> void with wrong arguments: (3,)
```

This seems to be somehow related to [PythonQt's](https://github.com/pathmann/PythonQt) metaTypeConverters.

Tested on Linux 64

**Comment by Bluscream** [comment]
Seems fixed to me. Reloading the scripts and reopening the console works fine. Reloading the pyTSon plugin itself and reopening the console, too.

**Comment by pathmann** [comment]
Fixed with https://github.com/pathmann/PythonQt/commit/7f3f6a97a76f5d035fb52db1f9039adb56f35192.

**Comment by pathmann** [comment]
Metatype-conversion seems to work now, but there is still something wrong with QEvent-based objects not being passed:

```
TypeError: mouseReleaseEvent() missing 1 required positional argument: 'e'
TypeError: mousePressEvent() missing 1 required positional argument: 'e'
TypeError: mouseReleaseEvent() missing 1 required positional argument: 'e'
TypeError: mousePressEvent() missing 1 required positional argument: 'e'
TypeError: mouseReleaseEvent() missing 1 required positional argument: 'e'
TypeError: mousePressEvent() missing 1 required positional argument: 'e'
TypeError: mouseReleaseEvent() missing 1 required positional argument: 'e'
TypeError: mousePressEvent() missing 1 required positional argument: 'e'
TypeError: mouseReleaseEvent() missing 1 required positional argument: 'e'
TypeError: mousePressEvent() missing 1 required positional argument: 'e'
TypeError: mouseReleaseEvent() missing 1 required positional argument: 'e'
TypeError: mousePressEvent() missing 1 required positional argument: 'e'
TypeError: mouseReleaseEvent() missing 1 required positional argument: 'e'
TypeError: keyPressEvent() missing 1 required positional argument: 'e'
TypeError: keyPressEvent() missing 1 required positional argument: 'e'
```

**Comment by pathmann** [comment]
Fixed with https://github.com/pathmann/PythonQt/commit/2e2764279017ab29c76c4fefc86632a019878eec.
