### ISSUE TITLE
Unable to load iconpack

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#72]
```
10/7/2017 05:21:48	ClientUI	Info	Calling plugin onMenuItemEvent: scHandlerID=1type=1, menuItemID=22, selectedItemID=509452	
10/7/2017 05:21:49	pytsonui.setupUi.	Error	Error loading iconpack: While reading from 'C:\\Users\\blusc\\AppData\\Roaming\\TS3Client\\gfx\\DarkenTS\\settings.ini' [line 259]: option 'arrow_left' in section 'gfxfiles' already exists	
10/7/2017 05:21:49	pyTSon	Error	Could not load icons: Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\channelGroupChanger\__init__.py", line 91, in __init__
    icons.open()
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\ts3client.py", line 266, in open
    self.settings.read(os.path.join(self.path, "settings.ini"))
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib\configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'C:\\Users\\blusc\\AppData\\Roaming\\TS3Client\\gfx\\DarkenTS\\settings.ini' [line 259]: option 'arrow_left' in section 'gfxfiles' already exists
```

Code in Question: https://github.com/Bluscream/pyTSon_plugins/blob/master/channelGroupChanger/__init__.py#L90

**Comment by Bluscream** [comment]
Thanks ^^
