### ISSUE TITLE
Error loading iconpack: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#88]
```
4/26/2018 14:19:33	pytsonui.setupUi.	Error	Error loading iconpack: 'charmap' codec can't decode byte 0x81 in position 39: character maps to <undefined>
...
4/26/2018 14:51:55	ClientUI	Info	Calling plugin onMenuItemEvent: scHandlerID=1type=2, menuItemID=32, selectedItemID=9	
4/26/2018 14:51:55	pytsonui.setupUi.	Error	Error loading iconpack: 'charmap' codec can't decode byte 0x81 in position 39: character maps to <undefined>	
4/26/2018 14:51:55	pyTSon	Error	Could not load icons: Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\channelGroupChanger\__init__.py", line 96, in __init__
    icons.open()
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\ts3client.py", line 271, in open
    self._loadEmoticonSettings(f)
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/include\ts3client.py", line 232, in _loadEmoticonSettings
    for line in f:
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 39: character maps to <undefined>
```
Iconpack in use: [teamspeak-dark](https://github.com/randomhost/teamspeak-dark/tree/master/iconpack/gfx/dark) + [Teamoji patch](http://yat.qa/ressourcen/)

**Comment by pathmann** [comment]
Please upload your emoticons.txt somewhere.

**Comment by Bluscream** [comment]
[emoticons.txt](https://github.com/pathmann/pyTSon/files/2207573/emoticons.txt)

**Comment by pathmann** [comment]
I can't reproduce this here, so this might be a windows only bug. Have to check that.
This might be related to #93.

**Comment by pathmann** [comment]
The problem is, that python uses the operating systems encoding system (which is mbcs on Windows).

Keeping this open, because zipped Iconpacks (are they still supported?) could be affected too.

**Comment by pathmann** [comment]
It seems, that zipped iconpacks wasn't affected.

**Comment by Bluscream** [comment]
Is this fixed now? I'm confused now

**Comment by pathmann** [comment]
Closed = fixed
